version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/sol-assistant/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: deploy/run_new.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: deploy/health_check.sh
      timeout: 180
      runas: ec2-user
  ValidateService:
    - location: deploy/switch.sh
      timeout: 180
      runas: ec2-user
