version: '3.8'

services:
  app:
    build: 
      context: .
      platform: linux/arm64
    container_name: sol-assistant-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - sol-network

  nginx:
    image: nginx:alpine
    platform: linux/arm64
    container_name: sol-assistant-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - sol-network

networks:
  sol-network:
    driver: bridge
