name: Build and Upload Docker Image

on:
  push:
    branches: [main]

env:
  S3_BUCKET_NAME: my-docker-bucket
  PROJECT_NAME: sol-assistant

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t sol-assistant .

      - name: Save Docker image to tar
        run: docker save sol-assistant > sol-assistant.tar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Docker image tar to S3
        run: aws s3 cp sol-assistant.tar s3://$S3_BUCKET_NAME/$PROJECT_NAME/sol-assistant-${{ github.sha }}.tar
