name: Build and Deploy Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker 빌드
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t sol-assistant .

      # 3. Docker 이미지를 tar로 저장
      - name: Save Docker image to tar
        run: docker save sol-assistant > sol-assistant.tar

      # 4. AWS 인증 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 5. appspec.yml과 tar를 zip으로 묶기
      - name: Create deployment zip
        run: |
          cp appspec.yml .
          zip -r sol-assistant-${{ github.sha }}.zip appspec.yml sol-assistant.tar

      # 6. S3 업로드
      - name: Upload zip to S3
        run: aws s3 cp sol-assistant-${{ github.sha }}.zip s3://sol-assistant-s3/sol-assistant-frontend/

      # 7. CodeDeploy 배포
      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name sol-assistant-deploy \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name frontend-zerotime-deploy \
            --s3-location bucket=sol-assistant-s3,bundleType=zip,key=sol-assistant-frontend/sol-assistant-${GITHUB_SHA}.zip
