name: Deploy Docker Client

on:
  push:
    branches: [main]

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy client with Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.MYPEMKEY }}
          port: 22
          debug: true
          timeout: 30s
          use_insecure_cipher: true
          script: |
            set -e
            echo "Testing SSH connection..."
            whoami
            pwd
            ls -la
            
            # 기존 디렉토리로 이동
            cd ~/SOL-Assistant-frontend
            
            # Git ownership 문제 해결 (한 번만 실행)
            git config --global --add safe.directory /home/ec2-user/SOL-Assistant-frontend
            
            # 환경변수 파일 생성 (필요시)
            # echo "${{ secrets.ENV_FILE_CLIENT }}" > .env.local
            
            # 최신 코드 가져오기
            git pull origin main
            
            # Docker 이미지 빌드 (ARM64 플랫폼 지정)
            docker build --platform linux/arm64 -t sol-assistant .
            
            # 기존 컨테이너 정리
            docker stop sol-assistant || true
            docker rm sol-assistant || true
            
            # 새 컨테이너 실행 (ARM64)
            docker run -d \
              --name sol-assistant \
              --platform linux/arm64 \
              -p 3000:3000 \
              --restart unless-stopped \
              sol-assistant
            
            # 컨테이너 상태 확인
            docker ps | grep sol-assistant
            
            # 컨테이너 로그 확인 (선택사항)
            echo "Container logs:"
            docker logs sol-assistant --tail 20
